name: Train and Log MLflow Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas

    # Run MLflow Project
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    # Ambil run_id terakhir
    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    
    # Build Docker Model
    - name: Build Docker Model
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "student-habits-image" 

    # Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     # Tag the Docker image
    - name: Tag Docker Image
      run: |
        docker tag student-habits-image ${{ secrets.DOCKER_HUB_USERNAME }}/student-habits-image:latest

    # Push Docker image to Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-habits-image:latest

    # Upload artefak (opsional)
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained_model
        path: mlruns/
